//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreThoiTrang63136126.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Script.Serialization;

    public partial class ChiTietHoaDon
    {
        public int MaHD { get; set; }
        public int IDCTSP { get; set; }
        public int SoLuongMua { get; set; }
        public decimal GiaMua { get; set; }
        public virtual SanPhamChiTiet SanPhamChiTiet { get; set; }
        [ScriptIgnore]
        public virtual HoaDon HoaDon { get; set; }
    }
}
