//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreThoiTrang63136126.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Script.Serialization;

    public partial class KichCo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KichCo()
        {
            this.SanPhamChiTiets = new HashSet<SanPhamChiTiet>();
        }
    
        public int MaKichCo { get; set; }
        public string TenKichCo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [ScriptIgnore]
        public virtual ICollection<SanPhamChiTiet> SanPhamChiTiets { get; set; }
    }
}
