//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreThoiTrang63136126.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoanQuanTri
    {
        public int ID { get; set; }
        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
        public bool LoaiTaiKhoan { get; set; }
        public string HoTen { get; set; }
        public bool TrangThai { get; set; }
    }
}
